// Force Rebuild
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { getMegaMenuData } from "@/lib/filters";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AuthProvider from "@/components/AuthProvider";
import Footer from "@/components/Footer";
import TopNavBar from "@/components/TopNavBar";
import StorefrontLayoutWrapper from "@/components/StorefrontLayoutWrapper";

export const dynamic = 'force-dynamic';
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const megaMenuData = await getMegaMenuData();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AuthProvider>
          <CartProvider>
            <StorefrontLayoutWrapper
              topNavBar={<TopNavBar megaMenuData={megaMenuData} />}
              footer={<Footer />}
            >
              {children}
            </StorefrontLayoutWrapper>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
